package org.kie.api.testday.kitchen
dialect "java"
import org.kie.api.testday.model.Room
import org.kie.api.testday.model.sensors.*


rule "sunny"
when
    $lightSensor: LightSensor(value > 85)
    Room(lightSensor == $lightSensor)
    Room($jal : jalousie, $lsv: lightSensor.value, $l : light, $jal != null, $l != null)
then
    modify($jal) {
        setShading($lsv - 10)
    };
    modify($l) {
        setBrightness(0)
    }
end



rule "fair"
when
    $lightSensor: LightSensor(value > 40, value <= 85)
    Room(lightSensor == $lightSensor)
    Room($jal : jalousie, $l : light, $jal != null, $l != null)
then
    modify($jal){
        setShading(0)
    };
    modify($l){
        setBrightness(0)
    }
end

rule "dusk"
when
    $lightSensor: LightSensor(value > 20, value <= 40)
    Room(lightSensor == $lightSensor)
    Room($jal : jalousie, $l : light, $jal != null, $l != null)
then
    modify($jal){
        setShading(0)
    };
    modify($l){
        setBrightness(100)
    }
end

rule "dark"
when
    $lightSensor: LightSensor(value <= 20)
    Room(lightSensor == $lightSensor)
    Room($jal : jalousie, $lsv : lightSensor.value, $l : light, $jal != null, $l != null)
then
    modify($jal){
        setShading(0)
    };
    modify($l){
        setBrightness(60 + ($lsv * 2))
    }
end